version: '3.9'

services:
  backend-app:
    container_name: graphql-book-catalog-server
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    build:
      dockerfile: ./.dockerfile
    env_file:
      - ./env
  articles_events_db:
    container_name: ${BOOK_CATALOG_DB_HOST}
    restart: always
    image: postgres:16.1-alpine
    command: -p ${BOOK_CATALOG_DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${BOOK_CATALOG_DB_PASSWORD}
      POSTGRES_DB: ${BOOK_CATALOG_DB_NAME}
      POSTGRES_USER: ${BOOK_CATALOG_DB_USER}
    ports:
      - ${BOOK_CATALOG_DB_PORT}:${BOOK_CATALOG_DB_PORT}
    volumes:
      - ${PWD}/data/book_catalog_db/:/var/lib/postgresql/data
